Load init fix issue 9 30
upb-lea/gym-electric-motor pull request #82
Opened 2020-08-17 17:53 UTC by GitPascalP

Fixed the initialization for the ExternalSpeedLoad and ConstantSpeedLoad.
Init in the environment is possible as a class instance (from requested load type) with the initializer as an argument, but Init should be also possible as keyword d for the ConstantSpeedLoad class with the load_intializer as an environment argument.
ExternalSpeedLoad is better supported by the initialization with an instance, due to the additional parameters for the speed profile.

2020-08-19 15:10 UTC, max-schenke requested changes
Behavior of constantSpeedLoad seems to be as intended. Behavior of externalSpeedLoad would need changes as no initializer is to be used there.

2020-08-19 15:10 UTC, max-schenke commented on gym_electric_motor/physical_systems/mechanical_loads.py
> +    initializer as an class parameter by instanziation
As stated in the further annotations, externalSpeedLoad should be changed such that it ignores the initializer. 
(also please correct typo instanziation -> instantiation)

2020-08-19 15:10 UTC, max-schenke commented on examples/external_speed_profile.py
> +# offset to avoid complicated spikes after a new episode start
The hints given in these comments do not match the intended behavior of the externalSpeedLoad. Information on that are noted my other annotations.

2020-08-19 20:39 UTC, GitPascalP commented on gym_electric_motor/physical_systems/mechanical_loads.py
> +        self._initializer['states']['omega'] = omega_initial
usage of an initializer is deleted. Speed profile at time 0 is used as initial value

2020-08-20 09:01 UTC, max-schenke requested changes
Minor changes still required to improve user feedback. Functionality seems to work as intended, thanks for your contribution!

2020-08-20 12:39 UTC, GitPascalP commented on gym_electric_motor/physical_systems/mechanical_loads.py
> +                      UserWarning)
changed as requested

2020-08-20 12:43 UTC, GitPascalP commented on gym_electric_motor/physical_systems/mechanical_loads.py
> -                 tau=1e-4, **kwargs):
to minimize error and the probability to have different tau's initialized it makes sense to just do it one time. I thought the functionality of the instantiate function in physcial_system.py targeted this case. The load is instantiated with tau and other kwargs, but the external speed load doesn't take the tau, given by the physical system and I'm not quite sure why.

2020-08-20 13:23 UTC, max-schenke approved these changes
Thanks to @GitPascalP for his fast reaction times. The necessary features should be working now.

2020-08-20 13:23 UTC, merged